/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-05-22 05:54:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class InscribirAlumno_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-2.1.4.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/codigo.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/estiloben.css\">\r\n");
      out.write("<title>Profesor - Inscribir Alumno</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"pa\">\r\n");
      out.write("\t\t<h1 class=\"titulo\">Profesor - Inscribir Alumno</h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"divMenu\"><br>\r\n");
      out.write("\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t<form>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"textPa\"Rut Alumno:\">Rut Alumno</label> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"email\" class=\"form-control\" id=\"rut\"placeholder=\"Rut Alumno\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"pull-right\">\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" class=\"btn btn-default pull-right\">Ingresar</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label class=\"textPa\"Informacion Alumno\">Informacion Alumno</label><br>\r\n");
      out.write("\t\t\t\t<br> <label for=\"Nombre Alumno:\">Nombre Alumno:</label> <input\r\n");
      out.write("\t\t\t\t\ttype=\"email\" class=\"form-control\" id=\"nombre\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"Nombre Alumno\" disabled>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label for=\"Apellido Alumno\">Apellido Alumno:</label> <input\r\n");
      out.write("\t\t\t\t\ttype=\"email\" class=\"form-control\" id=\"apellido\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"Apellido Alumno\" disabled>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label for=\"N° Matricula\">N° Matricula:</label> <input type=\"email\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control\" id=\"matricula\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"N° Matricula\" disabled>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label class=\"textPa\"col-md-4 control-label\" for=\"selectmultiple\">Cursos Disponibles</label>\r\n");
      out.write("\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t<select id=\"selectmultiple\" name=\"selectmultiple\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control\" multiple=\"multiple\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t<div class=\"pull-right\">\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" class=\"btn btn-default pull-right\">Inscribir</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- \r\n");
      out.write("\t\t<div class=\"divRut col-xs-4\">\r\n");
      out.write("\t\t\t<label class=\"textPa\">Rut Alumno</label><br> \r\n");
      out.write("\t\t\t<input type=\"text\"\tclass=\"form-control col-sm-8 rut\" placeholder=\"Rut\"><br>\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-info boton1\">Ingresar</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"divInfo col-xs-4\">\r\n");
      out.write("\t\t\t<label class=\"textPa\">Información del Alumno</label>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label>Nombre</label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"Nombre\" disabled> <label>Apellido</label> <input\r\n");
      out.write("\t\t\t\t\ttype=\"text\" class=\"form-control\" placeholder=\"Apellido\" disabled>\r\n");
      out.write("\t\t\t\t<label>N° Matrícula</label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"N° Matrícula\" disabled>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"divRamos col-xs-4\">\r\n");
      out.write("\t\t\t<label class=\"textPa\">Inscribir Curso</label>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label>Nombre</label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"Nombre\" disabled>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write(" -->\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
