/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-05-22 05:04:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class PagoMatricula_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<!-- Estilos -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/estiloSecretaria.css\">\r\n");
      out.write("<!-- JS -->\r\n");
      out.write("<title>Secretaria: Registro Matrícula</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- Titulo -->\r\n");
      out.write("\t<header class=\"text-center principal\">\r\n");
      out.write("\t<h1>Secretaria</h1>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<div id=\"menu\">\r\n");
      out.write("\t<a href=\"index.jsp\"><span><img src=\"images/Home.png\" alt=\"\"></span>Inicio</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Contenido -->\r\n");
      out.write("\t<div id=\"contenido\" class=\"container\">\r\n");
      out.write("\t\t<!-- Inicio panel -->\r\n");
      out.write("\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t<!-- Titulo panel -->\r\n");
      out.write("\t\t\t<div class=\"panel-heading\">Registro pago de matrícula por\r\n");
      out.write("\t\t\t\testudiante</div>\r\n");
      out.write("\t\t\t<!--Panel content-->\r\n");
      out.write("\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t<!--Inicio formulario busqueda-->\r\n");
      out.write("\t\t\t\t<label for=\"exampleInput\">Rut Estudiante:</label>\r\n");
      out.write("\t\t\t\t<form class=\"form-inline\" action=\"BuscarEstudiante\" method=\"get\">\r\n");
      out.write("\t\t\t\t     <!-- Incput captura de rut -->\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"ancho200 form-control\" name=\"rut\"\r\n");
      out.write("\t\t\t\t\t\trequired>\r\n");
      out.write("\t\t\t\t\t</imput>\r\n");
      out.write("\t\t\t\t\t <!-- Boton submit -->\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\">Ingresar</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<p id=\"validacionrut\">(Sin puntos y sin dígito verificador)</p>\r\n");
      out.write("\t\t\t\t <!-- Mensaje de error en caso que no se encuentra el estudiante -->\r\n");
      out.write("\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"imprimirestudiante alert alert-info\" role=\"alert\">\r\n");
      out.write("\t\t\t\t <!-- Se muetra la información del estudiante -->\r\n");
      out.write("\t\t\t\t<strong>Información del estudiante</strong>\r\n");
      out.write("\t\t\t\t<p>Nombre: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nombre}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</p>\r\n");
      out.write("\t\t\t\t<p>Apellido: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apellido}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</p>\r\n");
      out.write("\t\t\t\t<p>Rut: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rut}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</p>\r\n");
      out.write("\t\t\t\t<p>Estado Matrícula: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${estado}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--Inicio formulario registro-->\r\n");
      out.write("\t\t\t\t<form action=\"RegistrarPagoMatricula\" method=\"post\">\r\n");
      out.write("\t\t\t\t <!-- El rut ingresado en el input del formulario anterior se traspasa al siguiente input -->\r\n");
      out.write("\t\t\t\t\t<input id=\"rutregistro\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rut}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" type=\"text\" class=\"ancho200 form-control\" name=\"rutregistro\" required></imput>\r\n");
      out.write("\t\t\t\t\t<label for=\"exampleInput\">Monto a pagar:</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"input-group ancho200\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group-addon\">$</div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"exampleInputAmount\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"20.000\" disabled>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group-addon\">.00</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t <!-- Mensaje de respuesta -->\r\n");
      out.write("\t\t\t\t\t<div id=\"respuesta\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mensajeregistro}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t <!-- Boton submit -->\r\n");
      out.write("\t\t\t\t\t<button id=\"boton\" type=\"submit\" class=\"btn btn-primary btn-lg\"\r\n");
      out.write("\t\t\t\t\t\t>Registrar pago</button>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- Fin del panel -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Fin del contenido -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
