/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-05-22 05:55:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class PagoMensualidad_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\"> \r\n");
      out.write("  <!-- Estilos -->\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/estilocaso2.css\">\r\n");
      out.write("  <!-- JS -->\r\n");
      out.write("\r\n");
      out.write("  <!--<link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>-->\r\n");
      out.write("  <title>Secretaria: Registrar pago mensualidad</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <!-- Titulo -->\r\n");
      out.write("  <header class=\"text-center principal\">\r\n");
      out.write("    <h1>Secretaria</h1>\r\n");
      out.write("  </header>\r\n");
      out.write("  <div id=\"menu\">\r\n");
      out.write("  <a href=\"index.jsp\"><span><img src=\"images/Home.png\" alt=\"\"></span>Inicio</a>\r\n");
      out.write("  </div>\r\n");
      out.write("<!-- Contenido -->\r\n");
      out.write("<div id=\"contenido\" class=\"container\">\r\n");
      out.write("<!-- Inicio panel --> \r\n");
      out.write("  <div class=\"panel panel-default\">\r\n");
      out.write("    <!-- Titulo panel -->\r\n");
      out.write("        <div class=\"panel-heading\">Registrar pago mensualidad</div>\r\n");
      out.write("          <!--Panel content-->\r\n");
      out.write("        <div class=\"panel-body\">\r\n");
      out.write("          <!--Inicio formulario-->\r\n");
      out.write("          <form>  \r\n");
      out.write("          </form>\r\n");
      out.write("           <!--Maquetado -->\r\n");
      out.write("          <label for=\"exampleInput\">Rut Estudiante:</label>\r\n");
      out.write("                <div class=\"form-inline\">   \r\n");
      out.write("                   <input type=\"text\" class=\"ancho200 form-control\" name=\"rut\" required></imput>\r\n");
      out.write("                   <button type=\"submit\" class=\"btn btn-primary\">Ingresar</button>\r\n");
      out.write("                </div> \r\n");
      out.write("                <div class=\"separar\"></div>\r\n");
      out.write("           <div class=\"imprimirestudiante alert alert-info\" role=\"alert\">\r\n");
      out.write("         <!-- Se muetra la informaciÃ³n del estudiante -->\r\n");
      out.write("         \r\n");
      out.write("        <strong>InformaciÃ³n del estudiante</strong>\r\n");
      out.write("        <p>Nombre: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nombre}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</p>\r\n");
      out.write("        <p>Apellido: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apellido}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</p>\r\n");
      out.write("        <p>Rut: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rut}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</p>\r\n");
      out.write("        <p>Estado MatrÃ­cula: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${estado}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</p>\r\n");
      out.write("        </div>     \r\n");
      out.write("        \r\n");
      out.write("           <strong>Seleccione mes</strong>\r\n");
      out.write("          <select class=\"form-control ancho100\">\r\n");
      out.write("         \r\n");
      out.write("  <option>Enero</option>\r\n");
      out.write("  <option>Febrero</option>\r\n");
      out.write("  <option>3</option>\r\n");
      out.write("  <option>4</option>\r\n");
      out.write("  <option>5</option>\r\n");
      out.write("</select>\r\n");
      out.write("  <div class=\"separar\"></div>\r\n");
      out.write("         <p>Monto por curso: $10.000</p>\r\n");
      out.write("         <p>Total pagado: <strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${total}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</strong></p>\r\n");
      out.write("        </div>\r\n");
      out.write("          <button id=\"boton\" type=\"submit\" class=\"btn btn-primary btn-lg\"\r\n");
      out.write("            >Registrar pago</button>  \r\n");
      out.write(" <div class=\"separar\"></div>\r\n");
      out.write(" \r\n");
      out.write("  </div>  <!-- Fin del panel -->  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>  <!-- Fin del contenido -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
